name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk python3-distutils build-essential git python3-dev libffi-dev libssl-dev libltdl-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Buildozer and Kivy
      run: |
        pip install --upgrade cython virtualenv
        pip install buildozer[all]

    - name: Build APK
      run: |
        buildozer -v android debug
        echo "Build completed"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/
